// src/constants/roles.ts

export const Roles = [
  { label: "Admin", value: "ADMIN" },
  { label: "Guru", value: "GURU" },
  { label: "Wali Kelas", value: "WALI_KELAS" },
  { label: "Orang Tua", value: "ORANG_TUA" },
];


export enum JenisPelanggaran {
  TIDAK_MENGERJAKAN_TUGAS = "TIDAK_MENGERJAKAN_TUGAS",
  TERLAMBAT = "TERLAMBAT",
  MEMBOLOS = "MEMBOLOS",
  MEMBAWA_BARANG_TERLARANG = "MEMBAWA_BARANG_TERLARANG",
  BERTENGKAR = "BERTENGKAR",
  BERPAKAIAN_TIDAK_SESUAI = "BERPAKAIAN_TIDAK_SESUAI",
  MEROKOK = "MEROKOK",
  MENGGUNAKAN_HP_SAAT_PELAJARAN = "MENGGUNAKAN_HP_SAAT_PELAJARAN",
  MEMAKAI_PERHIASAN_BERLEBIHAN = "MEMAKAI_PERHIASAN_BERLEBIHAN",
  TIDAK_MENGIKUTI_UPACARA = "TIDAK_MENGIKUTI_UPACARA",
  TIDAK_MEMAKAI_SERAGAM = "TIDAK_MEMAKAI_SERAGAM",
  MELANGGAR_KETERTIBAN = "MELANGGAR_KETERTIBAN_LAINNYA"
}
