POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "1234444",
  "email": "tes@gmail.com",
  "role": "ADMIN",
  "password": "0987654321",
  "phoneNumber": "0867324332"
}


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "tes@gmail.com",
  "password": "0987654321"
}
